import type { NextPage } from 'next'
import Head from 'next/head'

const Account: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          Logging in
      </main>
    </div>
  )
}

export default Account
