/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require('fs');
const path = require('path');
const pkg = require('../lib/flagsmith/package.json');

const content = `// Auto-generated by write-version.js
export const SDK_VERSION = "${pkg.version}";
`;

fs.writeFileSync(path.join(__dirname, '../utils/version.ts'), content);
